# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34e26c40c08d26ddbfa87f83c527822a8e4d1bf6849467cb92f93dded8f1794434119f78228f2e9e8ab0d7f7c5078cd5913fa8c74e1cc68ee6683bfd8fc25fd

test:
  secret_key_base: a64bdd5eb5a9e033d826e97887f775dc6a04fb3a82dce38cd866bc093c3293287d43dff48e07b2b1721866b744f53f6669cd3bc0668cd53da0c8e453a4c54707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
